blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/Snupai/Mira-SwiftUI/discussions
    about: For general questions and discussions, please use GitHub Discussions.
